#EN PYTHON NO ES NECESARIO MENCIONAR UN TIPO DE VARIABLE
mensaje = "hola mundo"
print(mensaje)

#TAREA: REALIZAR UN PROGRAMA QUE MUESTRE POR CONSOLA EL SIGUIENTE MENSAJE
#ESTOY APRENDIENDO UN NUEVO LENGUAJE DE PROGRAMACION
#Y NO ME RENDIRE HASTA APRENDERLO

mensaje = "ESTOY APRENDIENDO UN NUEVO LENGUAJE DE PROGRAMACION"
mensaje2 = "Y NO ME RENDIRE HASTA APRENDERLO"
print(mensaje + "\n" + mensaje2)